{{- if eq (include "spire.install.enabled" .) "true" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-bundle
  namespace: {{ .Values.authentication.mutual.spire.install.namespace }}
{{- end }}
