{{- $installSpire := include "spire.install.enabled" . }}
{{- if and (eq $installSpire "true") .Values.authentication.mutual.spire.install.server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.authentication.mutual.spire.install.server.serviceAccount.name }}
  namespace: {{ .Values.authentication.mutual.spire.install.namespace }}
{{- end }}
