{{- $installSpire := include "spire.install.enabled" . }}
{{- if and (eq $installSpire "true") .Values.authentication.mutual.spire.install.agent.serviceAccount.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.authentication.mutual.spire.install.agent.serviceAccount.name }}
rules:
# Required cluster role to allow spire-agent to query k8s API server
- apiGroups: [ "" ]
  resources: [ "pods","nodes","nodes/proxy" ]
  verbs: [ "get" ]
{{- end }}
